### PR TITLE
Add input options to specify benchmark combinations

### PR DESCRIPTION
**Pull request by hernanmd**
Add run.sh and utils.sh with functions to manage input options.

The more relevant functions are:

- parse_cmd_line
- download_images
- generate_plots
- plot
- list

### CODE REVIEW

**Review by guillep — CHANGES_REQUESTED** [review]
thanks, it's good to see more structure in the project. 

could you extend the readme with usage instructions ?

also, how do these functions interplay with the benchmark parameters (iterations, bench script directory...). In particular, the list option and run functions should honot that variable, do they ? (should this be documented) 

also, I imagine this does not break any compatibility right ? 

thanks!

**Comment by PalumboN** [comment]
This PR tries to create a CLI for Benchy (instead of just executing `.sh`), which is nice! 👍 

Maybe we should take a look at a framework for CLIs, like https://github.com/SierraSoftworks/bash-cli.

For example, I don't want to write a `help` command (with "meta documentation" about the CLI itself) by hand. 
Or should be nice to have autocompletes and that kind of stuff.

**Comment by guillep** [comment]
Ok, so you mean this is backwards compatible.

I can move forward with this, open an issue to document this thing.

If we want a framework for this thing we can modify it later, I'm not against

**Review by guillep — APPROVED** [review]
Thanks!

**Pull request merged**
